### ISSUE TITLE
BN Marketplace version Crash?

### ISSUE THREAD

**Issue by Naville** [mrphrazer/obfuscation_detection#4]
```
....
sorted_functions = sorted(((f, scoring_function(f))
  File "Binary Ninja/repositories/community/plugins/mrphrazer_obfuscation_detection/obfuscation_detection/utils.py", line 53, in calc_average_instructions_per_block
    return num_instructions / num_blocks
ZeroDivisionError: division by zero

```

**Comment by mrphrazer** [comment]
Good catch, thanks. This happens if there are functions which have 0 basic blocks. It's fixed in 

https://github.com/mrphrazer/obfuscation_detection/commit/115510185867e612cca39908e34573c984f3a272

To test you'll have to checkout the git repo manually. I'll push a new version release in the next days

**Comment by mrphrazer** [comment]
New release is published. Should be in the plugin manager soon. I'll close the issue for now, feel free to open it if sth comes up
